---
title: "Logit Lens：把每一层的残差流投到词表，看答案怎样逐层成形"
slug: "04"
collection: "interpretability"
order: 4
summary: "第 03 章用 probe 回答了「信息在哪一层最强」，本章用 logit lens 回答另一半：「预测在哪一层成形」。把任意中间层的残差直接乘最终的 unembedding，得到「如果现在就停下来，模型会预测什么」，逐层投影就能看见答案 token 的概率从均匀爬到锁定。这把『信息可读』和『答案成形』两条线对上了，也给第 05 章的 activation patching 标好了精确打击坐标——该去哪层哪个位置做干预。"
topics:
  - "可解释性"
tags: []
createdAt: "2026-06-21T08:00:00.000Z"
updatedAt: "2026-06-21T08:00:00.000Z"
---

先把这章要做的事钉死成一句话：**残差流（residual stream，transformer 里那条贯穿全网、每层往上加东西的「信息高速公路」）在 pre-norm transformer 里是一个不断累加的 sum，而 unembedding（解嵌入，把向量变回词表 logit 的那层）只读最后那一份累加结果。logit lens 干的事，就是把这个「只读最后一份」的算子，偷偷拿去读中间某一份没加完的累加结果——问它：要是模型现在就被逼着开口，它会说哪个 token？**

这件事值钱在哪？第 03 章的 probe（探针，拿个小线性分类器去残差里捞标签）告诉你「第 L 层的残差里，答案信息够不够一个线性分类器读出来」。那是「信息在不在」。但信息在，不等于**模型自己**已经把它转成预测了——probe 是你外挂的读出头，模型出厂时用的读出头只有一个，就是那个 final LN + unembedding。logit lens 的全部价值，是它**只用模型自带的那个读出头**，所以它读到的东西，离「模型真正会输出什么」更近一步。第 03 章问「可读吗」，本章问「成形了吗」，下一句我们就会看到这两个问题的答案在深度轴上并不重合。

本章对应的可跑代码是 `examples/interpretability-from-scratch/src/stage04-logit-lens.ts`，编译后纯离线运行、固定种子、同一台机器逐字节可复现。下面引用的所有数字都来自它在已训练 checkpoint（`finalLoss=0.0005`，2 层）上的真实输出，任务是 modAdd(7)（`(a+b) mod 7`，vocab=8，token 7 是 `=`，唯一可评分的位置是 pos2 那个 `=`）。

## 为什么只能 lens「完整的残差」，不能 lens 组件输出

动手之前先划一条硬线，否则后面会投出一堆垃圾还不知道为什么。

`stage04-logit-lens.ts` 里枚举可投影点的函数 `residPoints` 只挑这几类：

```ts
function residPoints(nLayers: number): string[] {
  const pts = ["embed"];
  for (let l = 0; l < nLayers; l++) {
    pts.push(`blocks.${l}.resid_pre`); // stream entering block l (== embed for l=0)
    pts.push(`blocks.${l}.resid_mid`); // after attn write, before mlp
    pts.push(`blocks.${l}.resid_post`); // after full block l
  }
  return pts;
}
```

注意它**没有**收 `head_z` / `attn_out` / `mlp_out` 这些组件输出。源码注释把理由写死了：那些是组件**写进残差的增量（delta）**，不是「跑到这里为止的完整 sum」。unembedding 期待的输入是一份完整的残差流——你把一个 attention head 单独的输出向量丢给它，等于让一个习惯读「全班总分」的人去读「某一道题的得分」，量纲和分布都不对，投出来的 logit 没有任何「模型会预测什么」的含义。

所以记住这条不变量，它后面会反复救你：**lens 只投累加和（resid_pre / resid_mid / resid_post / embed），不投增量。** 这条线也是 logit lens 和 attribution（归因，把某个预测拆给各个组件）的分界——后者才去算单个 head 贡献了多少 logit，那是另一套方法（direct logit attribution），不在本章。

## 投影本身：借走 final LN + unembedding

真正的「lens」操作短到不可思议。`core/interp.ts` 里：

```ts
export function logitLens(model: TinyTransformer, residStream: Tensor): Tensor {
  return noGrad(() => {
    const normed = model.lnFinal.forward(residStream);
    return model.unembed.forward(normed);
  });
}
```

就两步：拿模型**最终那层** LayerNorm（`lnFinal`）归一化中间残差，再过 unembedding 得到 logit。`noGrad` 是因为这纯是观测、不训练，不用建图。

这里有个**容易被忽略却是整个方法成败关键的前提**：第二步用的 `lnFinal` 和 `unembed`，是模型在**最后一层**学出来的那一套权重。我们却拿它去归一化**中间层**的残差。这只有在一个假设下才说得通——中间层的残差和最终层的残差**活在同一个坐标系**里，所以同一个 LN + unembedding 才能通用地解读它们。

这个假设在 pre-norm transformer 里**部分成立**：因为残差流是累加的，`resid_post[L]` 包含了 `resid_post[L-1]` 的全部内容，方向上有连续性，越深越靠近最终坐标系。但它**不严格成立**——这正是 ✦ 专家钩子要展开的地方，我们留到 §失败模式。先看它在「成立的那一段」给出了什么。

## [1] 答案概率随深度的爬升曲线

8 个 probe 输入平均，正确答案 token 的概率沿残差流由浅到深：

```
P(answer)  shallow→deep
  embed | # 0.019
 L0.pre | # 0.019
 L0.mid | ######### 0.236
L0.post | ################# 0.471
 L1.pre | ################# 0.471
 L1.mid | ############################### 0.874
L1.post | #################################### 1.000
```

读这条曲线要会读三件事。

**第一，单调上升。** `first=0.0187 → last=0.9995`，中间没有掉下去过。这正是上一节那条不变量在数据上的回响：残差是累加的，每一层只往上叠信息，所以一个**忠实的** lens 应当看到答案概率大致单调逼近，而且一旦锁定就不再「解锁」。如果你在某个真实模型上 lens 出来的曲线疯狂上蹿下跳，第一反应不该是「这层好神秘」，而该是「我可能在 lens 一个不在输出坐标系的残差，或者这个模型不是我假设的那种 pre-norm 累加结构」——这是个诊断信号，不是发现。

**第二，台阶在哪儿。** `embed` 和 `L0.pre` 完全一样（0.019），这是对的——modAdd 任务里 `resid_pre` 在第 0 层入口就等于 embed，还没过任何 block，自然没变。第一个大跳发生在 `L0.mid`（0.236）和 `L0.post`（0.471）：第 0 层的 attention 和 MLP 把答案概率从「基本是噪声」抬到了接近一半。第二个台阶在 `L1.mid`（0.874）→ `L1.post`（1.000）。所以「计算在哪儿发生」的粗答案是：**两层都在干活，第 0 层把答案从无到有捞出来，第 1 层把它从「大概是」夯实到「就是」。**

**第三，0.019 这个起点意味着什么。** vocab=8，纯均匀分布下每个 token 是 0.125。embed 处答案概率 0.019，**比均匀还低**。这不是「模型还没想好」，这是个陷阱信号——我们到 §失败模式专门拆它，这里先记住：**起点比 chance 还低，是「自信地指向错误答案」的征兆，不是「无知」。**

## [2] 单例逐层演化：看见 lock-in

平均曲线好看，但抽象。挑一个具体输入 `[4,1,7]`（真答案 5）看模型「改主意」的全过程，这是 `stage04` 的 `lensInput` + `lockInIndex` 打出来的表：

```
point       top1   P(top1)   P(ans)  H(bits)
embed          0    0.7798   0.0087    1.275
L0.pre         0    0.7798   0.0087    1.275
L0.mid         2    0.6158   0.1304    1.617
L0.post        5✓   0.7469   0.7469    0.976  <- lock-in
L1.pre         5✓   0.7469   0.7469    0.976
L1.mid         5✓   0.9907   0.9907    0.095
L1.post        5✓   0.9995   0.9995    0.007
答案锁定层: L0.post (此后 lens top-1 稳定为正确答案 5)
```

逐行看模型在「想」什么：

- `embed`：top-1 是 token 0，概率 0.78，而真答案 5 只有 0.0087。**lens 在 embed 处自信地说错答案。**
- `L0.mid`：attention 写完了。top-1 变成 2（还是错），但 P(top1) 掉到 0.62、熵升到 1.617 bits——模型「动摇」了，旧的错误答案松动，新的还没立住。
- `L0.post`：MLP 写完。top-1 翻成 5（✓），且 P(ans)=0.747。这就是 **lock-in（锁定，lens 的 top-1 第一次变成正确答案且之后再不翻车的那个深度）**。
- `L1.*`：纯粹是把 5 从 0.747 夯到 0.9995，熵从 0.976 bits 压到 0.007 bits。第 1 层没有「改答案」，只在「加自信」。

`lockInIndex` 的定义里藏着一个被刻意做对的细节。它不是「top-1 第一次等于答案」，而是「**第一次等于答案、且之后一直是答案**」:

```ts
function lockInIndex(readings: LensReading[], answerToken: number): number {
  for (let i = 0; i < readings.length; i++) {
    let stable = true;
    for (let j = i; j < readings.length; j++) {
      if (readings[j].top1 !== answerToken) { stable = false; break; }
    }
    if (stable) return i;
  }
  return -1;
}
```

**为什么要加「且之后一直是」**：一个深度上偶然蹦对一次、下一层又翻回错的，不叫「解决」，叫巧合。我们要的是「此后稳定承诺」的那个深度。返回 `-1`（从未稳定锁定）是被允许的真实可能——代码没把它藏起来，这个 toy 上不常见，但在真实模型上「答案在中间层闪现又消失」是真事，不该被一个乐观的实现粉饰掉。

## [3] 锁定深度的分布：是「定点电路」还是「弥散」

单个例子的 lock-in 可能是它自己特殊。把 8 个输入各自的锁定点画成直方图，才能看出「答案在一个**一致**的深度被解决」还是「散得到处都是」：

```
lock-in depth histogram
L0.post | ############ 2.000
 L0.mid | ############ 2.000
 L1.mid | ######################## 4.000
```

8 个输入里：2 个在 `L0.mid` 锁定，2 个在 `L0.post`，4 个拖到 `L1.mid`。判断怎么下：锁定点**集中在「第 0 层后半 ~ 第 1 层中段」这个窄带**里，没有谁在 embed 就锁定（那会是泄漏），也没有谁拖到最后才锁。这说明这个 modAdd 电路的「答案成形」是**深度局部化**的——发生在一个可辨认的深度区间，而不是均匀摊在全网。这正是下一章要利用的东西：既然答案在 `L0` 后段到 `L1` 中段成形，patching（打补丁式干预）就该把火力集中在这几层这几个位置，而不是盲扫。

⚠ 但要诚实：这是 8 个 sample 的分布，不是 8000 个。`L1.mid` 占一半（4/8）这个**具体比例**我不会当成稳定结论——它完全可能是小样本下的抖动。可迁移的是**形状**（存在一个集中的锁定窄带），不是这张直方图的精确高度。这跟全书的诚实边界一致：toy 给你方法的形状，不给你能外推的绝对数。

## 失败模式：embed 处的 lens 是「自信地错」✦

现在拆开本章最该讲透的反直觉点。回到 §投影那节埋的伏笔：lens 假设中间残差和最终残差**同坐标系**，所以才能共享 `lnFinal` + `unembed`。在最浅的 `embed` 处，这个假设**最不成立**——embed 是「输入坐标系」里的向量，还没经过任何 block 把它推向输出坐标系，而 `lnFinal` 的均值/方差统计是在**最终**残差流上学出来的。拿最终层的归一化统计去归一化 embed，是个 **off-distribution（分布外，喂给一个算子它训练时没见过的输入分布）** 操作。

直觉会以为：分布外 → lens 应该「糊」→ 高熵、谁都拿不准。**实测打脸**。`stage04` 的 [4] 段：

```
均匀分布熵上限 = log2(8) = 3.000 bits  (作对照: 熵越低=越"自信")
embed lens : 平均熵 1.275 bits  top-1命中真答案 0/8  (chance≈1.0)
最深 lens  : 平均熵 0.007 bits  top-1命中真答案 8/8
```

读这三行的方法，是把「自信」和「正确」**当成两个独立的轴**：

- embed lens 的熵只有 1.275 bits，远低于均匀分布的 3.000 bits——它**看起来很自信**，分布有明显的峰。
- 但它的 top-1 命中真答案 **0/8**。chance≈1.0（8 个输入随机猜该中 1 个），它一个都没中，**比随机还差**。
- 最深 lens：熵 0.007 bits（极自信）+ 8/8 全中。这才是「自信且正确」。

结论一句话：**embed lens 是「自信地错」**。它投出来的那个尖峰不是「模型的早期想法」，是噪声里的伪峰——early 残差不在输出坐标系，用 `lnFinal` 的统计去归一化它属于 off-distribution，归出来的分布碰巧有个峰，但峰指向的 token 跟真答案无关。

**这是 logit lens 最危险的坑，也是新手最容易栽的地方**：把 lens 的「自信」（低熵、有尖峰）当成「正确」。`stage04` 注释把判据写死了——**唯一能判断 lens 在某个深度是否忠实的，是 top-1 vs 真答案，不是熵、不是峰高。** 熵只告诉你 lens 有多「拿得准」，不告诉你它「拿对没拿对」。正确读法：lens 只在**足够深、已经进入输出坐标系**的残差上才忠实；浅层的 lens 读数，除非你用 top-1-vs-ground-truth 验证过，否则当它不存在。

回头看 [1] 那个 0.019 的起点和 [2] 那个 `embed: top1=0, P=0.78` 的行——现在它们都对上了：那不是「模型还没想好」（那会是高熵、接近 0.125 的均匀），那是「lens 自己在分布外瞎指一个错 token 还指得很坚决」。

## tuned lens：给每层学一个校正 ⚡

「embed lens 不忠实」直接引出原始 logit lens 的根本局限，也引出当前这条研究主线。

原始 lens 对每一层都**复用同一套** `lnFinal` + `unembed`，相当于假设「所有层都在同一坐标系」。这个假设越往浅越破。**tuned lens（调校透镜）** 的修法很朴素：**不假设同坐标系，而是为每一层单独学一个仿射变换**，把该层的残差先「翻译」到输出坐标系，再过 unembedding。也就是给第 L 层配一个学出来的 `A_L · resid + b_L`，让翻译后的向量在最终 unembedding 下表现忠实。

最小预告版本（这是 tuned lens 思路的玩具化，不是它的完整实现）：拿一批输入，对某一层的残差和「最终 logit」之间拟合一个线性映射，让该层的投影对齐最终行为。这样浅层不再「自信地错」，而是「被校正到忠实」。这条线再往前推还有 **Patchscopes**——不再线性投影，而是把目标残差**塞进模型自己的另一段前向**里，让模型用自然语言「解释」这个残差，比线性 lens 更忠实也更通用。logit lens → tuned lens → Patchscopes，是「读残差」这件事从启发式走向更可信工具的一条清晰演进。

⚡ 但这里有个**目前没有通用解**的开放问题：**一个残差到底「忠实」到什么程度，没有不依赖 ground-truth 的内禀度量。** 我们这章判忠实，靠的是「top-1 命中真答案」——可那要求你**已经知道答案**。在真实任务上你恰恰不知道答案（否则要 lens 干嘛）。tuned lens 用「拟合后预测分布逼近真实下一 token 分布」当代理目标，但「拟合得好」和「真实反映了该层在算什么」并不等价——你可能学出一个把噪声也翻译得很像样的映射，反而**掩盖**了该层其实没在算答案这个事实。「如何在没有 ground-truth 的前提下，独立判断一个 lens/probe 读到的是模型的真实计算、而非被读出方法自己注入的结构」，是机制可解释性里悬而未决的核心难题之一，正在被研究，没有公认答案。

## 诚实边界：这个 toy 为什么对 lens「太友好」

最后把可迁移的和不可迁移的分清楚，免得你拿这章的漂亮曲线去真实大模型上撞墙。

`stage04` 自己声明了边界：本 toy 只有 2 层、`dModel` 小、**LayerNorm 的影响小**，所以原始 lens 的忠实度**高于**真实大模型。真实的 12~96 层模型里，LN 的重定心（recentering）效应、各层坐标系的漂移都比这里严重得多，往往**非用 tuned lens / LN 重定心不可**，原始 lens 在中间层会给出明显不忠实的读数。这就是为什么 tuned lens 在大模型上是刚需，而在这个 toy 上「原始 lens 已经够用」——不是我们偷懒,是这个 LayerNorm 影响小的小模型恰好让原始 lens 仍然忠实。

**可迁移的是形状，不是绝对数**：

- ✅ P(answer) 随深度近似单调上升 + 存在一个可辨认的锁定深度（窄带）——这个**定性形状**在真实模型上也成立。
- ❌ `embed=0.019 → last=0.9995` 这种干净的绝对概率、`L1.mid` 占锁定一半这种精确比例——**偏乐观**，别外推。
- ✅ 「lens 的自信 ≠ 正确，唯一判据是 top-1 vs ground-truth」——这条**方法论**到哪都成立，越是大模型越要守。

---

到这里，第 03 章的「信息在哪层最强」和本章的「预测在哪层成形」就对上了一半：信息**可读**的深度（probe 能捞出来）通常**早于**答案**成形**的深度（lens 锁定），中间那段「信息在了但模型还没把它转成预测」的过程，正是后面要拆的电路在干的活。

但全章要记住：**logit lens 仍然是「读」，不是「证」。** 它告诉你「答案在 `L0.post` 这一带锁定」，这是一个强烈的相关性观察——可它没**证明**是 `L0` 的某个组件**导致**了答案成形，万一是更早的某处早就决定好、`L0.post` 只是第一个被 lens 读出来的深度呢？要从「相关」走到「因果」，得动手干预：把那个位置的激活换掉，看预测变不变。这正是第 05 章 activation patching 要做的事——而 logit lens 已经替它把坐标标好了：**去 `L0.post` 到 `L1.mid` 这个锁定窄带做干预，那里是答案成形的精确打击区。**
